### ISSUE TITLE
How to use this package with ros kinect.

### ISSUE THREAD

**Issue by lff12940** [VisualComputingInstitute/2D_lidar_person_detection#1]
I tried to run the ROS package with ROS Kinect,  but encountered the following problems:

NODES
  /
    dr_spaam_ros (dr_spaam_ros/node.py)

auto-starting new master
process[master]: started with pid [1578]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 76205f44-410b-11eb-b03e-8030494bc3f1
process[rosout-1]: started with pid [1593]
started core service [/rosout]
process[dr_spaam_ros-2]: started with pid [1609]
Traceback (most recent call last):
  File "/home/liuliu/catkin_ws/src/dr_spaam_ros/scripts/node.py", line 4, in <module>
    from dr_spaam_ros.dr_spaam_ros import DrSpaamROS
  File "/home/liuliu/catkin_ws/src/dr_spaam_ros/src/dr_spaam_ros/dr_spaam_ros.py", line 9, in <module>
    from dr_spaam.detector import Detector
  File "build/bdist.linux-x86_64/egg/dr_spaam/detector.py", line 4, in <module>
  File "build/bdist.linux-x86_64/egg/dr_spaam/model/__init__.py", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dr_spaam-1.2.0-py2.7.egg/dr_spaam/model/dr_spaam_fn.py", line 207
    frame_id = f"{batch_dict['frame_id'][ib]:06d}"
                                                 ^
SyntaxError: invalid syntax
[dr_spaam_ros-2] process has died [pid 1609, exit code 1, cmd /home/liuliu/catkin_ws/src/dr_spaam_ros/scripts/node.py __name:=dr_spaam_ros __log:=/home/liuliu/.ros/log/76205f44-410b-11eb-b03e-8030494bc3f1/dr_spaam_ros-2.log].

What  cause this problem and how can i solve it? 

Thanks.

**Comment by Pandoro** [comment]
ROS Kinetic uses python 2.7 by default and this is python 3 syntax.

One option is to build Ros yourself using python 3. But maybe Dan can
explain how he runs the node.

**Comment by danjia21** [comment]
Hi @lff12940 , Alex is correct. This code requires python >= 3.8. Python2 is no longer supported by PyTorch > 1.4.

You can keep your ROS build as it is (no need to rebuild), and create a python virtual environment with the required python version. Then call the `roslaunch dr_spaam_ros dr_spaam_ros.launch` inside the virtual environment.

**Comment by Pandoro** [comment]
Yes, I also recalled doing it with a virtual environment in some way, but
forgot the details. In practice, and especially this case, it will mostly
work fine. The clean solution would be to build it with python 3 thought.

**Comment by lff12940** [comment]
OK，thanks. I will try to solve it with a virtual environment.

**Comment by lff12940** [comment]
But there is a problem I don’t really understand. The code requires python3, but If I want to launch the ros node I need python2. How to use a virtual environment to ensure that two python versions are used in one node?

**Comment by danjia21** [comment]
> But there is a problem I don’t really understand. The code requires python3, but If I want to launch the ros node I need python2. How to use a virtual environment to ensure that two python versions are used in one node?

`roslaunch` works with Python3. I suspect `rosnode` will also work, but I did not verify it.

**Comment by lff12940** [comment]
> > But there is a problem I don’t really understand. The code requires python3, but If I want to launch the ros node I need python2. How to use a virtual environment to ensure that two python versions are used in one node?
> 
> `roslaunch` works with Python3. I suspect `rosnode` will also work, but I did not verify it.

Yes, your suggestions are very helpful. I set up a virtual environment and solved this problem.
Thanks.
