### ISSUE TITLE
JackRabbot dataset

### ISSUE THREAD

**Issue by Lyy369** [VisualComputingInstitute/2D_lidar_person_detection#12]
HI，could you provide the JackRabbot dataset, since I coludn't  download  the dataset from https://jrdb.stanford.edu/

**Comment by danjia21** [comment]
Hi @Lyy369 the dataset is now here https://jrdb.erc.monash.edu/

**Comment by Lyy369** [comment]
Thanks, but which one should I download? 
<img width="271" alt="image" src="https://github.com/VisualComputingInstitute/2D_lidar_person_detection/assets/76517302/ee80d700-c563-484b-87e6-0da3bab51113">

**Comment by danjia21** [comment]
The pointcloud, labels, and rosbags are needed. You can download the full dataset unless space is an issue.

**Comment by ai-winter** [comment]
Hello, @Lyy369 
I'm sorry, but I am unable to obtain the download permission for the JRDB dataset. Can you please share the data with me? Thank you very much.

**Comment by Pandoro** [comment]
Please go through the official channels to obtain a dataset. These
guardrails are there for a reason and should not be circumvented.
