### ISSUE TITLE
JRDB dataset

### ISSUE THREAD

**Issue by ai-winter** [VisualComputingInstitute/2D_lidar_person_detection#13]
Hello, thanks for your contribution!

I have downloaded the `train timestamps` of the JRDB dataset but found that only `frames_img.json` and `frames_pc.json` are available. The `frames_pc_im_laser.json` mentioned in the code is missing. How can I resolve this issue?

![image](https://github.com/VisualComputingInstitute/2D_lidar_person_detection/assets/61778098/f0c423bc-e192-45d0-9471-ead82ce1d55f)

**Comment by Pandoro** [comment]
I'm not super familiar with the code, but a simple search instantly pointed me to the `setup_jrdb_dataset.py` file. Did you run that? If not, please follow the readme, and if you did, you'll sadly have to debug why it didn't create all the files.

**Comment by ai-winter** [comment]
Hello, @Pandoro 

Thanks for your response, I will try it again.
