### ISSUE TITLE
hello ,how to show inference result, thank you

### ISSUE THREAD

**Issue by gwadvisable** [VisualComputingInstitute/2D_lidar_person_detection#14]
hello ,how to show inference result, thank you!!

**Comment by Pandoro** [comment]
Search for `plotting` and dig around a little bit there, or run the ros node and visualize the visualization topics using rviz. The latter should work out of the box, if you want to use the other code, this was mostly for internal visualizations and never properly documented as far as I know, it should be straight forward to understand though.
