### ISSUE TITLE
 Unexpected key(s) in state_dict: "conv_box.weight", "conv_box.bias" using DR_SPAAM

### ISSUE THREAD

**Issue by chumpblocckami** [VisualComputingInstitute/2D_lidar_person_detection#15]
Hi, 
i cloned the repo and I tried to run _self_supervised_person_detection/jrdb_dr_spaam_with_bev_box_e20.pth_ with this parameters:

> 
> CONF_THRESH: float = 0.8
> STRIDE: int = 1  # use this to skip laser points
> DETECTOR_MODEL: str = "DR-SPAAM"
> PANORAMIC_SCAN: bool = False
> LASER_FOV: int = 270
> USE_GPU: bool = True if DEVICE == "cuda" else False
> PLACEHOLDER_VALUE: float = 29.99

But it gives me an error: 

![image](https://github.com/VisualComputingInstitute/2D_lidar_person_detection/assets/12396148/d4f4f98e-a202-44ff-b99b-3d7eccdf721a)

it seems that something is wrong with the loaded model (maybe a different version?). 

I also tried with **"DROW3"** as detector_model and the same parameters, but it fails with even more errors:

![image](https://github.com/VisualComputingInstitute/2D_lidar_person_detection/assets/12396148/ed9653c5-9ef2-4db3-a38e-fb8be2f7d2bb)

Others models, such as _self_supervised_person_detection/ckpt_jrdb_ann_ft_drow3_e40.pth_, works fine.

Can you please me?

Thanks for your time!

**Comment by Pandoro** [comment]
I don't have time to dig into it in detail, but the obvious issue is that you are loading a model that was trained to predict bird's eye view bounding boxes. By default DR-SPAAM doesn't do that, so it's missing the conv that predicts the boxes and thus you get the unexpected key(s) error. Briefly searching for `conv_box` reveals that the `DR_SPAAM` class takes `use_box` as a parameter. Looking at the `Detector` class though, you can see that there is no nice way to pass this as an argument in the current code. I'm guessing this is mainly just there as a comparison for some of our experiments in the 2D vs 3D LiDAR paper we did, but Dan never meant to really support this as a polished option. You should be able to simply modify the code though and pass `use_box=True` in the `Detector` class where the `DR_SPAAM` detector is created and then you should be able to load the checkpoint.

As I said though, we just had this for a comparison and it's not a model we actually worked with in practice, so I don't want to vouch for how good this will work.

Closing this for now. Feel free to re-open if you have further questions.
