### ISSUE TITLE
 About the location of the net_cfg.yaml file

### ISSUE THREAD

**Issue by Ze-HaoLee** [VisualComputingInstitute/2D_lidar_person_detection#17]
Hello author, when I ran the code "python bin/train.py --cfg net_cfg.yaml [--ckpt ckpt_file.pth --evaluation]", I found that I did not find the corresponding "net_cfg.yaml" , may I ask where the "net_cfg.yaml" is?

**Comment by Pandoro** [comment]
This is literally discussed in the README.
