### ISSUE TITLE
modify the path to the pre-trained checkpoint 

### ISSUE THREAD

**Issue by 112233445566666** [VisualComputingInstitute/2D_lidar_person_detection#19]
Hello, when I perform “roslaunch dr_spaam_ros dr_spaam_ros.launch“Terminal display：
... logging to /home/wyfjyc/.ros/log/d999db3c-27cf-11ef-b688-bd75d45442bb/roslaunch-omnisky-415311.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://omnisky:37595/

SUMMARY
========

PARAMETERS
 * /dr_spaam_ros/conf_thresh: 0.5
 * /dr_spaam_ros/detector_model: DROW3
 * /dr_spaam_ros/panoramic_scan: True
 * /dr_spaam_ros/publisher/detections/latch: False
 * /dr_spaam_ros/publisher/detections/queue_size: 1
 * /dr_spaam_ros/publisher/detections/topic: /dr_spaam_detections
 * /dr_spaam_ros/publisher/rviz/latch: False
 * /dr_spaam_ros/publisher/rviz/queue_size: 1
 * /dr_spaam_ros/publisher/rviz/topic: /dr_spaam_rviz
 * /dr_spaam_ros/stride: 1
 * /dr_spaam_ros/subscriber/scan/queue_size: 1
 * /dr_spaam_ros/subscriber/scan/topic: /person_pts
 * /dr_spaam_ros/weight_file: /home/jia/ckpts/c...
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    dr_spaam_ros (dr_spaam_ros/node.py)

auto-starting new master
process[master]: started with pid [415319]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to d999db3c-27cf-11ef-b688-bd75d45442bb
process[rosout-1]: started with pid [415338]
started core service [/rosout]
process[dr_spaam_ros-2]: started with pid [415345]
Traceback (most recent call last):
  File "/home/wyfjyc/catkin_ws/src/2D_lidar_person_detection/dr_spaam_ros/scripts/node.py", line 10, in <module>
    DrSpaamROS()
  File "/home/wyfjyc/catkin_ws/src/2D_lidar_person_detection/dr_spaam_ros/src/dr_spaam_ros/dr_spaam_ros.py", line 17, in __init__
    self._detector = Detector(
  File "/home/wyfjyc/anaconda3/envs/graph/lib/python3.8/site-packages/dr_spaam-1.2.0-py3.8.egg/dr_spaam/detector.py", line 52, in __init__
  File "/home/wyfjyc/anaconda3/envs/graph/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/wyfjyc/anaconda3/envs/graph/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/wyfjyc/anaconda3/envs/graph/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/jia/ckpts/ckpt_jrdb_ann_drow3_e40.pth'
[dr_spaam_ros-2] process has died [pid 415345, exit code 1, cmd /home/wyfjyc/catkin_ws/src/2D_lidar_person_detection/dr_spaam_ros/scripts/node.py __name:=dr_spaam_ros __log:=/home/wyfjyc/.ros/log/d999db3c-27cf-11ef-b688-bd75d45442bb/dr_spaam_ros-2.log].
log file: /home/wyfjyc/.ros/log/d999db3c-27cf-11ef-b688-bd75d45442bb/dr_spaam_ros-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
------weight_file: "/home/jia/ckpts/ckpt_jrdb_ann_drow3_e40.pth"Where is this path? How do you set it up?

**Comment by Pandoro** [comment]
As the readme states, we provide pretrained checkpoints for different models. You will have to download the checkpoint of a model you want to run and replace the path to wherever you save it on your machine. A quick search for the path in the code could have shown you that the path is located in the `dr_spaam_ros.yaml` file that is being loaded by the launch file. You can replace the path there.
