### ISSUE TITLE
Static obstacles cause lots of false positives

### ISSUE THREAD

**Issue by Shuijing725** [VisualComputingInstitute/2D_lidar_person_detection#7]
Hi,

Based on the provided demo and my own experiments with real-time lidar data, many small clusters of lidar points that are actually obstacles (such as furniture and uneven walls) are mistakenly detected as humans. I tried to increase the confidence threshold to 0.99 but this problem still occur. Is there any way to fix it besides re-training or finetuning the model with my own data?

**Comment by Pandoro** [comment]
Hi Shuijing,

back when we deployed the model, I do recall some false positives, but there weren't many. I'm assuming you are using a different lidar model, potentially with a different resolution? You could try to adjust some parts of the code to make the input to the actual trained network more similar to our training data. But all of this is a bit hacky. If you see lots of false positives, the only real way to get around it, will likely be to retrain the model on your own dataset. 

For this you could also have a look at some of our [later work](https://github.com/VisualComputingInstitute/2D_lidar_person_detection) where we train the detector in a "self-supervised" fashion, based on detections in a calibrated RGB camera. That might potentially be interesting.

**Comment by Shuijing725** [comment]
Hi Alexander,

Thank you for your suggestions! To match the network inputs, could you clarify which parts of the code to adjust?

**Comment by Pandoro** [comment]
Hi Shujing,

I just realized I linked the repo you asked this question about. For some odd reason I thought it was in a different repo. Sorry for that mixup, as such my advise is also a bit wrong. For DR-SPAAM I just quickly checked the ROS code and most of it should already be taken care of. It's important that the angular increment of the scanner is set correctly, but as far as I can tell from the code this should be included in the lidar scan messages. After that, the cutouts should be sampled in the same way, regardless of the exact lidar model. However, the trained models might still not work very well on out of distribution inputs. One more thing that is a bit special about DR-SPAAM though, is the fact that the attention is evaluated in a [local window](https://github.com/VisualComputingInstitute/2D_lidar_person_detection/blob/1a365cddaa95338e4abf658ff224b1aa3b57abe2/dr_spaam/dr_spaam/model/dr_spaam.py#L16) around each point. As far as I can tell from the code this is not handled automatically and it might be worth playing around with that in the ROS node a bit by also providing a larger or smaller window size, depending on whether your lidar has a larger or smaller angular increment. Lastly, there is the temporal frequency of your scanner. If that differs a lot from what the model was trained on, this can also have a quite negative effect. For that there is no real setting you could try to change though.

All that of course assumes you are using ROS. If you don't, make sure you properly specify the angular increment when you create the cutouts and still play around with the window size of the attention.

If none of that helps, I think you will sadly have to retrain/fine-tune your model. As far as I recall, when fine-tuning, we didn't have major success. We did use "fairly large" datasets though and training from scratch just worked better. If you only have a small handful of annotated scans, fine-tuning might be the better way to go.
